[package]
name = "raytracing_series"
version = "0.3.0"
authors = ["Ahmad Kabani <ahmadkabani@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
clap = "3.0.0-beta.1"
rand_chacha = "0.2.2"
image = "0.23.4"
rayon = "1.3.0"
num_cpus = "1.13.0"
